### ISSUE TITLE
TO-DO List

### ISSUE THREAD

**Issue by Awe1alex** [Awe1alex/loginMEVN#1]
- [ ] Login page design

- [ ] Login page mobile design

- [ ] Edit profile page design

- [ ] Front-end authorization requests and .then

- [ ] Back end initialization

- [ ] Mongo/Mongoose initialization

- [ ] Backend authorization

- [ ] Backend user logged checker
